#In below workflow registry env is optional, you can directly build image without passing registry name 
#eg: docker build -t ${{ vars.USERNAME }}/${{ env.image }}:0.1 .   which translates to docker build -t pavan36/webapp-github-actions .

name: cicd-reuse
on: 
  workflow_dispatch:
  push: 
    branches: 
      - main
jobs:
    Image-Build:
      uses: ./.github/workflows/reusable-workflow.yml
      secrets: inherit 

    Deploy:
      runs-on: ubuntu-latest
      env:
       registry: docker.io
       image: webapp-github-actions
      needs: Image-Build
      steps:
        - name: Docker login
          run: |
            docker login --username=${{ vars.USERNAME }} --password=${{ secrets.PASSWORD }}
        - name: Image  and Deploy
          run: |
            docker pull ${{ vars.USERNAME }}/${{ env.image }}:0.1
            docker run -d ${{ env.image }}

