#In below workflow registry env is optional, you can directly build image without passing registry name 
#eg: docker build -t ${{ vars.USERNAME }}/${{ env.image }}:0.1 .   which translates to docker build -t pavan36/webapp-github-actions .

name: cicd
on: workflow_dispatch
jobs:
    Image-Build:
        env:
            registry: docker.io
            image: webapp-github-actions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: docker-login
              run: |
               docker login --username=${{ vars.USERNAME }} --password=${{ secrets.PASSWORD }}
            - name: Image-Build
              run: |
                docker build -t ${{ env.registry }}/${{ vars.USERNAME }}/${{ env.image }}:1.0 .
            - name: Image-List
              run: |
               docker images
    Deploy:
      runs-on: ubuntu-latest
      needs: Image-Build
      steps:
        - name: Docker login
          run: |
            docker login --username=${{ vars.USERNAME }} --password=${{ secrets.PASSWORD }}
        - name: Image  and Deploy
          run: |
            docker pull ${{ vars.USERNAME }}/${{ env.image }}:0.1
            docker run -d ${{ env.image }}

