name: First Workflow
on: push
jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: read file
        run: cat README.md
      - name: print-vm-details
        run: |  
           cat /etc/os-release
           uname -r