name: GHA-reuse-code-checkout-caller
on: 
  workflow_dispatch:
  push: 
    branches: 
      - main
jobs:
    Code-check:
      uses: ./vector-agent-aggregator/.github/workflows/GHA-reuse-code-checkout.yml
