name: Matrix-test
on:
    workflow_dispatch: 
jobs:
    deploy:
        timeout-minutes: 2
        strategy:
            max-parallel: 4
            matrix:
                os: [ubuntu-latest,ubuntu-20.04,windows-latest]
                images: [hello-world,alpine]
                exclude:
                    - os: windows
                      images: alpine
                include: 
                    - os: centos
                      images: busybox
        runs-on: ${{ matrix.os }}
        steps:
            - name: Get the docker-info
              run: docker info
            - name: Run the images on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}

              


            
