name: Multi-job-workflow
on: push
jobs:
  create-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a test file
        run: |
         echo "This is multi-job file" > testfile.txt
         pwd
         ls -lart
      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: testfile
          path: testfile.txt
  list-job:
    needs: create-job
    runs-on: ubuntu-latest
    steps:
        - name: download-artifacts
          uses: actions/download-artifact@v3
          with:
            name: testfile
        - name: list the files
          run: |
           ls -lart
           pwd
        - name: create-another-file
          run: |
            echo "second test file" > secondfile.txt
            pwd
  read-job:
    needs: list-job
    runs-on: ubuntu-latest
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v3
        with:
          name: testfile
      -  name: print the file
         run: cat testfile.txt


