name: First Workflow
on: push
jobs:
  create-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a test file
        run: |
         echo "This is multi-job file" > testfile.txt
      - name: upload-artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: testfile
          path: testfile.txt
  list-job:
    needs: create-job
    runs-on: ubuntu-latest
    steps:
        - name: download-artifacts
          uses: actions/download-artifacts@v3
          with:
            name: testfile
        - name: list the files
          run: ls -lart
  read-job:
    needs: list-job
    runs-on: ubuntu-latest
    steps:
      - name: download-artifacts
        uses: actions/download-artifacts@v3
        with:
          name: testfile
      -  name: print the file
         run: cat testfile.txt


