# 1st job(create-job) checkout code, create a file (testfile.txt) and upload the artifact to 2nd second job(list-job),
#2nd second checkout the code, download the artifact from 1st job , create a new file secondfile.txt and upload the artifact to the 3rd job (read job)
#3rd job, download the artifact from 2nd job and print the both files created on 1st and 2nd job.

#Note:  If you have multiple jobs which creates artificats at every job and if the next corresponding job needs to read the artificates
#you need to use both upload and download artifact in previous job. Eg: In below case 1st job creates one file and it is downloaded 
#on second job and second job creates new file, so, again it was uploaded in 2nd job and downloaded in 3rd job.  


name: Multi-job-workflow
on: push
jobs:
  create-job:                              
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a test file
        run: |
         echo "This is multi-job file" > testfile.txt
         pwd
         ls -lart
      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: testfile
          path: testfile.txt
  list-job:                              # This job will checkout the code, download the artificat from 1st job(create-job)
    needs: create-job
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: download-artifacts
          uses: actions/download-artifact@v3
          with:
            name: testfile
        - name: list the files
          run: |
           ls -lart
           pwd
        - name: create-another-file
          run: |
            echo "second test file" > secondfile.txt
            pwd
        - name: upload-list-job-artifact
          uses: actions/upload-artifact@v3
          with:
            name: list-job
            path: .
  read-job:
    needs: list-job
    runs-on: ubuntu-latest
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v3
        with:
          name: list-job
      -  name: print the file
         run: |
           ls -lart 
           cat testfile.txt
           cat secondfile.txt
           pwd