name: reusable-workflow
on: 
  workflow_call: 
    inputs:
      image:
        required: false
        default: webapp-github-actions
        type: string
  workflow_dispatch: 
  
jobs:
    Image-Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: docker-login
              run: |
               docker login --username=${{ vars.USERNAME }} --password=${{ secrets.PASSWORD }}
            - name: Image-Build
              run: |
                docker build -t ${{ env.registry }}/${{ vars.USERNAME }}/${{ inputs.image }}:1.0 .
              env:
                image: ${{ inputs.reuse-webapp }}
            - name: Image-List
              run: |
               docker images