name: reusable-workflow
on: 
  workflow_call: 
  workflow_dispatch: 
jobs:
    Image-Build:
        env:
            registry: docker.io
            image: webapp-github-actions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: docker-login
              run: |
               docker login --username=${{ vars.USERNAME }} --password=${{ secrets.PASSWORD }}
            - name: Image-Build
              run: |
                docker build -t ${{ env.registry }}/${{ vars.USERNAME }}/${{ env.image }}:1.0 .
            - name: Image-List
              run: |
               docker images