# This workflow is to understand how env variables and secrets should be defined in a workflow. 
# username variable is defined in the repo variables space,and it should be refer as vars.variable ,if we were to use in the workflow (line 16)
# Similar to env variable, secrets are defined in the repo secret space and it should be refer as secrets.secretname in workflow (line 16)
# varible can also be declared at worflow,job and steps level, In below case it was declared in the worflow level(line 9,10)
# as i required those at build and deploy jobs and whatever the varibles you defined in the workflow(pipleline) can be accessed as env.variable name (line 20).
# Note: if you have variables unique to jobs and steps, define at the same..

name: variable-secret workflow
on: 
  workflow_dispatch:  
env:
  image: webapp
  registry: docker.io
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run: docker login --username=${{ vars.USERNAME }} --password=${{ secrets.PASSWORD }}
      - name: Build the image
        run: echo docker build -t ${{ env.registry }}/${{ vars.USERNAME }}/${{ env.image }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: deploy the image
        run: echo docker run -d ${{ env.registry }}/${{ vars.USERNAME }}/${{ env.image }}
    
                                
