name: variable-secret workflow
on: push
env:
  image: webapp
  registry: docker.io
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run: docker login --username=${{ vars.USERNAME }} --password=${{ secrets.PASSWORD }}
      - name: Build the image
        run: echo docker build -t ${{ env.registry }}/${{ vars.USERNAME }}/${{ env.image }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: deploy the image
        run: echo docker run -d ${{ env.registry }}/${{ vars.USERNAME }}/${{ env.image }}
    
                                
